name: "brandOptics AI Code Review"
description: "Runs the brandOptics AI neural-intelligence engine against your PR."
branding:
  icon: "zap"     
  color: "green"   

inputs:
  openai_key:
    description: "Your OpenAI API key"
    required: true
  github_token:
    description: "GitHub Actions token (pass via workflow)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai PyGithub flake8 flake8-json
      shell: bash

    - name: Set up Node & ESLint
      uses: actions/setup-node@v4
      with:
        node-version: "18"

    - name: Install ESLint
      run: npm install -g eslint
      shell: bash

    - name: Install ShellCheck
      run: |
        sudo apt-get update && sudo apt-get install -y shellcheck
      shell: bash

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "7.0.x"

    - name: Install Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Prepare linter-reports folder
      run: mkdir -p .github/linter-reports
      shell: bash

    - name: Run ESLint (JS/TS/React/Angular)
      run: |
        eslint '**/*.js' '**/*.jsx' '**/*.ts' '**/*.tsx' \
          --format json \
          --output-file .github/linter-reports/eslint.json || true
      shell: bash

    - name: Run Flake8 (Python)
      run: |
        flake8 . --format=json --output-file .github/linter-reports/flake8.json || true
      shell: bash

    - name: Run ShellCheck (Shell scripts)
      run: |
        find . -type f -name "*.sh" \
          | xargs -I {} sh -c "shellcheck -f json {} >> .github/linter-reports/shellcheck.json" || true
      shell: bash

    - name: Fetch dependencies (Flutter/Dart)
      run: |
        if [ -f "pubspec.yaml" ]; then
          flutter pub get
        fi
      shell: bash

    - name: Run Dart/Flutter Analyzer
      run: |
        if [ -f "pubspec.yaml" ] && [ -d "lib" ]; then
          dart analyze --format=json > .github/linter-reports/dartanalyzer.json || true
        else
          echo '{"diagnostics":[]}' > .github/linter-reports/dartanalyzer.json
        fi
      shell: bash

    - name: Run the AI review
      run: python "$GITHUB_ACTION_PATH/.github/scripts/bobot_review.py"
      shell: bash
      env:
        OPENAI_API_KEY:   ${{ inputs.openai_key }}
        GITHUB_TOKEN:     ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}